# Generated by Django 4.2.16 on 2024-11-03 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio_converter', '0001_initial'),
        ('text_processing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcription',
            name='call_at',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='user',
        ),
        migrations.AddField(
            model_name='transcription',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcription',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='audio_converter.voicerecording'),
        ),
    ]
